// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['Dialog'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetDownloadSize(arg1) {
  return window['go']['main']['App']['GetDownloadSize'](arg1);
}

export function GetVideoDetails(arg1) {
  return window['go']['main']['App']['GetVideoDetails'](arg1);
}
