// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function GetDownloadProgress():Promise<number>;

export function GetDownloadSize(arg1:string):Promise<number>;

export function GetVideoDetails(arg1:string):Promise<string>;
